variable "env" {}
#variable "cidr_block" {}
variable "default_vpc_id" {}
variable "vpc" {}
#variable "main_vpc" {}
variable "docdb" {}
variable "rds" {}
variable "redis" {}
#variable "instance_class" {}
#variable "engine_version" {}